import { TouristObject } from "@/types/object";

export const mockObjects: TouristObject[] = [
  {
    id: "1",
    name: "Altyn Bulak Glamping",
    coordinates: { lat: 43.2220, lng: 76.8512 },
    address: "Иле-Алатауский национальный парк, Алматинская область",
    category: "luxury_glamping",
    contacts: {
      phone: "+7 777 123 4567",
      email: "info@altynbulak.kz",
      whatsapp: "+7 777 123 4567",
      instagram: "@altynbulak_glamping"
    },
    website: "https://altynbulak.kz",
    description: "Премиальный глэмпинг с панорамным видом на горы Заилийского Алатау. Современные юрты с всеми удобствами, ресторан с национальной кухней, spa-зона.",
    capacity: 8,
    priceRange: { min: 45000, max: 85000 },
    photos: ["https://images.unsplash.com/photo-1628992029221-7ea0a9d9a1f5"],
    rating: 4.8,
    reviewsCount: 127,
    infrastructure: ["Wi-Fi", "Паркинг", "Ресторан", "SPA", "Бассейн"],
    status: "verified",
    lastUpdated: "2025-01-15",
    priorityScore: 9.2,
    leadPriority: "hot",
    activityScore: 95,
    dataCompleteness: 100,
    popularity: 92,
    commercialPotential: 88
  },
  {
    id: "2",
    name: "Kokzhailau Guest House",
    coordinates: { lat: 43.1333, lng: 77.0333 },
    address: "ур. Кокжайляу, Алматы",
    category: "family_guesthouse",
    contacts: {
      phone: "+7 708 234 5678",
      whatsapp: "+7 708 234 5678",
      instagram: "@kokzhailau_house"
    },
    description: "Уютный семейный дом в горах недалеко от Алматы. Идеально для семейного отдыха с детьми. Детская площадка, барбекю зона, домашняя кухня.",
    capacity: 12,
    priceRange: { min: 15000, max: 30000 },
    photos: [],
    rating: 4.5,
    reviewsCount: 64,
    infrastructure: ["Паркинг", "Кухня", "Барбекю", "Детская площадка"],
    status: "in_progress",
    lastUpdated: "2025-01-14",
    priorityScore: 7.8,
    leadPriority: "warm",
    activityScore: 78,
    dataCompleteness: 75,
    popularity: 68,
    commercialPotential: 72
  },
  {
    id: "3",
    name: "Eco Camp Charyn",
    coordinates: { lat: 43.3461, lng: 79.0861 },
    address: "Чарынский каньон, Алматинская область",
    category: "ecotourism",
    contacts: {
      phone: "+7 701 345 6789",
      email: "contact@ecocharyn.kz",
      telegram: "@ecocharyn"
    },
    website: "https://ecocharyn.kz",
    description: "Эко-лагерь на территории Чарынского национального парка. Экологичное размещение, походы, наблюдение за природой, экскурсии по каньону.",
    capacity: 20,
    priceRange: { min: 12000, max: 25000 },
    photos: ["https://images.unsplash.com/photo-1504280390367-361c6d9f38f4"],
    rating: 4.6,
    reviewsCount: 89,
    infrastructure: ["Эко-туалеты", "Кухня", "Костровая зона", "Экскурсии"],
    status: "verified",
    lastUpdated: "2025-01-16",
    priorityScore: 8.5,
    leadPriority: "hot",
    activityScore: 85,
    dataCompleteness: 88,
    popularity: 84,
    commercialPotential: 79
  },
  {
    id: "4",
    name: "Nomad Yurt Camp",
    coordinates: { lat: 42.8833, lng: 74.6167 },
    address: "Киргизский хребет, Жамбылская область",
    category: "ethno_yurt",
    contacts: {
      phone: "+7 702 456 7890",
      whatsapp: "+7 702 456 7890",
      instagram: "@nomad_yurt_kz"
    },
    description: "Традиционный юрточный лагерь с аутентичным казахским гостеприимством. Национальная кухня, конные прогулки, знакомство с культурой кочевников.",
    capacity: 15,
    priceRange: { min: 18000, max: 35000 },
    photos: [],
    rating: 4.7,
    reviewsCount: 43,
    infrastructure: ["Национальная кухня", "Конные прогулки", "Традиционные юрты"],
    status: "new",
    lastUpdated: "2025-01-17",
    priorityScore: 8.1,
    leadPriority: "hot",
    activityScore: 72,
    dataCompleteness: 68,
    popularity: 76,
    commercialPotential: 85
  },
  {
    id: "5",
    name: "Alpine Refuge Shymbulak",
    coordinates: { lat: 43.2867, lng: 77.0794 },
    address: "Горнолыжный курорт Шымбулак, Алматы",
    category: "mountain_house",
    contacts: {
      phone: "+7 727 123 4567",
      email: "info@alpinerefuge.kz"
    },
    website: "https://alpinerefuge.kz",
    description: "Горный домик на высоте 2260 метров. Идеально для любителей горных лыж зимой и треккинга летом. Рядом с подъемниками.",
    capacity: 6,
    priceRange: { min: 35000, max: 60000 },
    photos: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4"],
    rating: 4.9,
    reviewsCount: 156,
    infrastructure: ["Wi-Fi", "Ресторан", "Сауна", "Лыжное хранилище"],
    status: "verified",
    lastUpdated: "2025-01-15",
    priorityScore: 9.0,
    leadPriority: "hot",
    activityScore: 92,
    dataCompleteness: 95,
    popularity: 91,
    commercialPotential: 90
  },
  {
    id: "6",
    name: "Lake View Cottage Kolsay",
    coordinates: { lat: 42.9667, lng: 78.3333 },
    address: "Озеро Кольсай, Алматинская область",
    category: "ecotourism",
    contacts: {
      phone: "+7 705 567 8901",
      whatsapp: "+7 705 567 8901"
    },
    description: "Коттеджи на берегу озера Кольсай. Рыбалка, катание на лодках, пешие маршруты. Тишина и природа.",
    capacity: 10,
    priceRange: { min: 20000, max: 40000 },
    photos: [],
    rating: 4.4,
    reviewsCount: 38,
    infrastructure: ["Паркинг", "Кухня", "Лодки", "Мангал"],
    status: "new",
    lastUpdated: "2025-01-16",
    priorityScore: 7.3,
    leadPriority: "warm",
    activityScore: 65,
    dataCompleteness: 62,
    popularity: 71,
    commercialPotential: 74
  },
  {
    id: "7",
    name: "Steppe Horizon Yurts",
    coordinates: { lat: 50.2833, lng: 57.1667 },
    address: "Костанайская область, степная зона",
    category: "ethno_yurt",
    contacts: {
      phone: "+7 709 678 9012",
      instagram: "@steppe_horizon"
    },
    description: "Юрточный комплекс в степи с традиционным казахским укладом жизни. Кумыс, бешбармак, соколиная охота.",
    capacity: 12,
    priceRange: { min: 15000, max: 28000 },
    photos: [],
    reviewsCount: 22,
    infrastructure: ["Традиционная кухня", "Конные прогулки", "Соколиная охота"],
    status: "new",
    lastUpdated: "2025-01-13",
    priorityScore: 6.8,
    leadPriority: "warm",
    activityScore: 58,
    dataCompleteness: 55,
    popularity: 64,
    commercialPotential: 68
  },
  {
    id: "8",
    name: "Green Valley Resort",
    coordinates: { lat: 43.0333, lng: 76.9667 },
    address: "Талгарский район, Алматинская область",
    category: "family_guesthouse",
    contacts: {
      phone: "+7 701 789 0123",
      email: "info@greenvalley.kz",
      whatsapp: "+7 701 789 0123"
    },
    website: "https://greenvalley.kz",
    description: "Загородный комплекс для семейного отдыха. Бассейн, детские аниматоры, ресторан, спортивные площадки.",
    capacity: 30,
    priceRange: { min: 25000, max: 50000 },
    photos: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb"],
    rating: 4.6,
    reviewsCount: 203,
    infrastructure: ["Wi-Fi", "Бассейн", "Ресторан", "Детская площадка", "Спортплощадки"],
    status: "verified",
    lastUpdated: "2025-01-17",
    priorityScore: 8.7,
    leadPriority: "hot",
    activityScore: 88,
    dataCompleteness: 92,
    popularity: 87,
    commercialPotential: 82
  }
];
